### PR TITLE
Update to version 0.7.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by awvwgk** [comment]
@conda-forge-admin, please rerender

**Comment by awvwgk** [comment]
@dhirschfeld @andreyz4k Happy to help co-maintain this package.

**Comment by dhirschfeld** [comment]
Thanks @awvwgk - this was on my TODO list... but it's a long list! 😬

Any reason you didn't just bump to the latest version? No harm in publishing this one, but then I guess we'd want to also publish the latest

**Review by dhirschfeld — APPROVED** [review]
LGTM!

https://github.com/microsoft/knack/blob/v0.7.0/setup.py#L14-L22

**Comment by awvwgk** [comment]
I will go through all versions until latest once this is merged.

**Comment by dhirschfeld** [comment]
I took the liberty of adding `automerge`/`update-grayskull` - it helps minimise the maintenance burden by automating the updates. With `grayskull` it's pretty good a following any changes to the deps.

**Comment by dhirschfeld** [comment]
> I will go through all versions until latest once this is merged.

Do you *need* that? I'd recommend just publishing the latest after this - which should be able to be done automatically with an admin command.

**Comment by awvwgk** [comment]
I guess there is no need, but better to have all versions on conda-forge which are also on PyPI for completeness.

**Comment by dhirschfeld** [comment]
I'd be inclined to apply the YAGNI principle, but obviously, feel free to back-populate any missing versions now that you're a maintainer! :)

**Pull request merged**
